### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by PaulDance** [n4r1b/ferrisetw#131]
Hi!

#129 fixes an issue I've encountered: would it be possible to publish a new version including it, please? In the meantime, obviously consuming this crate _via_ a Git dependency is possible and functional, it simply is a little less ergonomic in various places.

Thanks in advance!

**Comment by n4r1b** [comment]
Sorry for the late reply! I will be publishing a new version ASAP! :)

**Comment by PaulDance** [comment]
Cool, thanks!

**Comment by n4r1b** [comment]
Just published v1.2.0 😄
