### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by Cody-Duncan** [n4r1b/ferrisetw#48]
This repository doesn't have a license file. I see that the Cargo.toml says "MIT or Apache 2.0".

Recommend adding LICENSE.md files to more clearly indicate the license.

**Comment by daladim** [comment]
Thanks for the notice, this will be included in the next releases.

(not related, but you may have seen that there is a ferrisetw 1.0 brewing in the [`next_major_version` branch](https://github.com/n4r1b/ferrisetw/tree/next_major_version) that you may want to have a look at if you're planning to use ferrisetw)
