### ISSUE TITLE
Invalid widestring pointer

### ISSUE THREAD

**Issue by 0xlane** [n4r1b/ferrisetw#60]
hello, I have used the code of this commit(#42). An `PropertyError("Invalid widestring pointer")` error occurred when I used the following code: 

```rust
TryParse::<String>::try_parse(&parser, "appname")
```

This problem will not occur if i switch to the previous commits.

**Comment by daladim** [comment]
Hello, I had identified this bug as well.

This happens because I thought every unicode strings would be aligned on 16-bits boundaries, but this assumption turned out to be wrong. And thus, an optimization I made is incorrect.
I'll correct this in the days to come, stay tuned 😄
