### ISSUE TITLE
Enable non-threaded or blocking trace session

### ISSUE THREAD

**Issue by pathtofile** [n4r1b/ferrisetw#84]
Hi,
I really like the work you've done here, good job!

For my purposes, I usually want to start a trace, and run it until I quit the program. In the current implementation Ferris spawns a new anonymous thread to do the processing, which means I need to either do a 'sleep forever' or 'wait for user input' hack.

Would it be possible to either:
* Run a trace in the same thread (e.g. 'blocking' mode); or
* Expose the spawned thread in the `Trace` struct, so I could do a .join on it

**Comment by daladim** [comment]
Hello, this is already possible in ferrisetw 1.0 :)

See my reply from #85 to see how to do so (basically, use a branch from this repo rather than the published 0.1 version from crates.io)
